//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OleViewDotNet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbghelp.dll")]
        public string DbgHelpPath32 {
            get {
                return ((string)(this["DbgHelpPath32"]));
            }
            set {
                this["DbgHelpPath32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbghelp.dll")]
        public string DbgHelpPath64 {
            get {
                return ((string)(this["DbgHelpPath64"]));
            }
            set {
                this["DbgHelpPath64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("srv*https://msdl.microsoft.com/download/symbols")]
        public string SymbolPath {
            get {
                return ((string)(this["SymbolPath"]));
            }
            set {
                this["SymbolPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SymbolsConfigured {
            get {
                return ((bool)(this["SymbolsConfigured"]));
            }
            set {
                this["SymbolsConfigured"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuidFormat {
            get {
                return ((string)(this["GuidFormat"]));
            }
            set {
                this["GuidFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ParseStubMethods {
            get {
                return ((bool)(this["ParseStubMethods"]));
            }
            set {
                this["ParseStubMethods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResolveMethodNames {
            get {
                return ((bool)(this["ResolveMethodNames"]));
            }
            set {
                this["ResolveMethodNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProxyParserResolveSymbols {
            get {
                return ((bool)(this["ProxyParserResolveSymbols"]));
            }
            set {
                this["ProxyParserResolveSymbols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ParseRegisteredClasses {
            get {
                return ((bool)(this["ParseRegisteredClasses"]));
            }
            set {
                this["ParseRegisteredClasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ParseClients {
            get {
                return ((bool)(this["ParseClients"]));
            }
            set {
                this["ParseClients"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ParseActivationContext {
            get {
                return ((bool)(this["ParseActivationContext"]));
            }
            set {
                this["ParseActivationContext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatabasePath32 {
            get {
                return ((string)(this["DatabasePath32"]));
            }
            set {
                this["DatabasePath32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatabasePath64 {
            get {
                return ((string)(this["DatabasePath64"]));
            }
            set {
                this["DatabasePath64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableSaveOnExit32 {
            get {
                return ((bool)(this["EnableSaveOnExit32"]));
            }
            set {
                this["EnableSaveOnExit32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableSaveOnExit64 {
            get {
                return ((bool)(this["EnableSaveOnExit64"]));
            }
            set {
                this["EnableSaveOnExit64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableLoadOnStart32 {
            get {
                return ((bool)(this["EnableLoadOnStart32"]));
            }
            set {
                this["EnableLoadOnStart32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableLoadOnStart64 {
            get {
                return ((bool)(this["EnableLoadOnStart64"]));
            }
            set {
                this["EnableLoadOnStart64"] = value;
            }
        }
    }
}
