//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OleViewDotNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OleViewDotNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;Python&quot; extensions=&quot;.py&quot;&gt;
        ///	
        ///	&lt;Properties&gt;
        ///		&lt;Property name=&quot;LineComment&quot; value=&quot;#&quot;/&gt;
        ///	&lt;/Properties&gt;
        ///	
        ///	&lt;Digits name=&quot;Digits&quot; color=&quot;DarkBlue&quot;/&gt;
        ///
        ///	&lt;RuleSets&gt;
        ///		&lt;RuleSet ignorecase=&quot;false&quot;&gt;
        ///			
        ///			&lt;Delimiters&gt;()[]{}@,:.`=;+-*/% &amp;amp;|^&amp;gt;&amp;lt;&lt;/Delimiters&gt;
        ///			
        ///			&lt;Span name=&quot;DocComment&quot; color=&quot;Green&quot;&gt;
        ///				&lt;Begin&gt;&quot;&quot;&quot;&lt;/Begin&gt;
        ///				&lt;End&gt;&quot;&quot;&quot;&lt;/End&gt;
        ///			&lt;/Span&gt;
        ///			
        ///			&lt;Span name=&quot;SingleQuoteDocComment&quot; color=&quot;Green&quot;&gt;
        ///				&lt;Begin&gt;&apos;&apos;&apos;&lt;/Begin&gt;
        ///				&lt;End&gt;&apos;&apos;&apos;&lt;/End&gt;
        ///			&lt;/Span&gt;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PythonHighlightingRules {
            get {
                return ResourceManager.GetString("PythonHighlightingRules", resourceCulture);
            }
        }
    }
}
